(() => {
  "use strict";
  const PX = 2;
  function parseSprite(rows, palette) {
    const h = rows.length;
    const w = rows[0].length;
    const pixels = new Array(h * w);
    rows.forEach((row, y) => {
      const chars = [...row];
      for (let x = 0; x < w; x++) {
        const ch = chars[x] || ".";
        pixels[y * w + x] = Object.prototype.hasOwnProperty.call(palette, ch) ? palette[ch] : null;
      }
    });
    return bakeSprite({ w, h, pixels });
  }
  function bakeSprite(sprite) {
    const { w, h, pixels } = sprite;
    const canvas = document.createElement("canvas");
    canvas.width = w; canvas.height = h;
    const c = canvas.getContext("2d");
    c.imageSmoothingEnabled = false;
    for (let i = 0; i < pixels.length; i++) {
      const color = pixels[i];
      if (!color) continue;
      c.fillStyle = color;
      c.fillRect(i % w, Math.floor(i / w), 1, 1);
    }
    sprite.canvas = canvas;
    return sprite;
  }
  const SPRITES = {
    // kael
    kael: parseSprite([
      "......................AAAAA.....................",
      "......................AAAAA.....................",
      ".....................AAAAAAA....................",
      "......................AAAAA.....................",
      "...................BBBAAAAABBB..................",
      ".................BBBBBCCACBBBBBB................",
      "................BBBBDBCCCCBBBBBBB...............",
      "...............DBBDBBDCCCCBBDBBBBB..............",
      "..............BBBBBBBBBDBDBBDDDBBBB.............",
      ".............BBDDBEBBDBBBBBBDDBBBDBB............",
      ".............BBBBEBEBDBBBBBDBBBBDBBB............",
      "............BBBDBBBBDBBBDBBBDDDBBDBBB...........",
      "............BBBBDBDBBBBBBBBBBBBBBBBBB...........",
      "............DDDBBBBBDBDBDDDBDBBDDBBBB...........",
      "...........BBBBBBDBBBBBBBBBBBBBBBBBBBB..........",
      "...........BBDFFFFFFFFFFFFFFFFFFFFBBBB..........",
      "...........BBBFFGGGGGGFFFFGGGGGGFFBBBB..........",
      "............DBFFGGHGGGFFFFGGHGGGFFDBB...........",
      "............BBFFGGGGGGFFFFGGGGGGFFDBB...........",
      "............BBFFFFFFFFFFFFFFFFFFFFBBB...........",
      ".........F...BFFFFFFFFFFFFFFFFFFFFBB...F........",
      "......FFFFFFFBBBDBBBBBBBBBDBBBBBBBBBFFFFFFF.....",
      ".....FFFFFFFFFBBBBDDDBBBDBBBBBBDDBBFFFFFFFFF....",
      "....FFFFFFFFFFFBBBBBBBBDBBBBBBBBBBFFFFFFFFFFF...",
      "....FFFFFFFFFFFDBBBBBBBBBBBDBBBBBHFFFFFFFFFFF...",
      "...FFFFFFFFFFFFFHBBBBBBBBBBBBBBBHFFFFFFFFFFFFF..",
      "...FFFFFFFFFFFFFHHHBBBBBBBBBBBHHHFFFFFFFFFFFFF..",
      "...FFFFFFFFFFFFFHFHFFHHBBBHFHFHHHFFFFFFFFFFFFF..",
      "...FFFFFFFFFFFFFHHHHHHHHHHHHFHHHHFFFFFFFFFFFFF..",
      "..FFFFFFFFFFFFFFFHHHHHHHHHFHFHHHFFFFFFFFFFFFFFF.",
      "..FFFFFFFFFFFFFFFHFHHHFHHHHHHFHFFFFFFFFFFFFFFFF.",
      "..FFFFFFFFFFFFFFFHHHHHHHHHHHHHHHFFFFFFFFFFFFFFF.",
      "...FFFFFFFFFFFFFFFHHHHHFHHHHHHFHHFFFFFFFFFFFFF..",
      "...FFFFFFFFFFFFFHHHHHHHFHHFHHHFHHFFFFFFFFFFFFF..",
      "...FFFFFFFFFFFFFHFFFHHHFHHHFHFHHHFFFFFFFFFFFFF..",
      "...FFFFFFFFFFFFFFHFHHHFFFFHFHHFFHFFFFFFFFFFFFF..",
      "....FFFFFFFFFFFCCCCCCCCAACCCCCCCCCFFFFFFFFFFF...",
      "....FFFFFFFFFFFCCCCCCCCCCCCCCCCCCCFFFFFFFFFFF...",
      ".....FFFFFFFFFCCCCCCCCCCCCCCCCCCCCHFFFFFFFFF....",
      "......FFFFFFFFHFFHHHHHHHHHHHFFHHHFF.FFFFFFF.....",
      ".........F...HHHHHFFHHHHHHFHHFHHHHF....F........",
      ".............FFHHHHHHHHHHHHHHHHFHHH.............",
      "...............FFFHHHHHHHHHHHHHFF...............",
      "...............FFFFHHHHHHHHHHHFFF...............",
      "...............FFFFFFF.HHHFFFFFFF...............",
      "...............FFFFFFF....FFFFFFF...............",
      "...............FFFFFFF....FFFFFFF...............",
      "...............FFFFFFF....FFFFFFF...............",
      "...............FFFFFFF....FFFFFFF...............",
      "...............FFFFFFF....FFFFFFF...............",
      "...............CCCCCCC....CCCCCCC...............",
      "...............CCCCCCC....CCCCCCC...............",
      "...............CCCCCCC....CCCCCCC...............",
      "................................................"
    ], { '.':null,'A':'#88ccff','B':'#3aa0ff','C':'#1e90ff','D':'#1e6acc','E':'#8ad0ff','F':'#050818','G':'#e8f0ff','H':'#0a1030' }),

    // zara
    zara: parseSprite([
      "................................................",
      "..............AA.AA.AA.AA.AA.AA.AA..............",
      "..............AA.AA.AA.AA.AA.AA.AA..............",
      "..............AA.AA.AA.AABAA.AA.AA..............",
      "..............AA.AABAABAABAABAA.AA..............",
      "..............AA.AABAABAABAABAABAA..............",
      "..............AABAABAABAABAABAABAA..............",
      "..............AABAABAABAABAACAABAA..............",
      "..............BBBBBBBBBAACBBCCCBBBB.............",
      ".............BBCCBDBBCBAABBBCCBBBCBB............",
      ".............BBBBDBDBCBAABBCBBBBCBBB............",
      "............BBBCBBBBCBBBCBBBCCCBBCBBB...........",
      "............BBBBCBCBBBBBBBBBBBBBBBBBB...........",
      "............CCCBBBBBCBCBCCCBCBBCCBBBB...........",
      "...........BBBBBBCBBBBBBBBBBBBBBBBBBBB..........",
      "...........BBCBBEEEEEEBBBCEEEEEECBBBBB..........",
      "...........BBBBBEEFEEEBBBCEEFEEEBBBBBB..........",
      "............CBBBEEEEEEBBCBEEEEEEBBCBB...........",
      ".EEEEE......BBBBEEEEEEBBBBEEEEEEBCCBB.....EEEEE.",
      ".EEEEE......BBBCBBBBCBCBCBBCBBBBCBBBB.....EEEEE.",
      ".EGGGE.......BBBCBBBBBCCBBBBBBCBBBBB......EGGGE.",
      ".EGGGE.......BBBCBBBBBBBBBCBBBBBBBBB......EGGGE.",
      ".EGGGE........BBBBCCCBBBCBBBBBBCCBB.......EGGGE.",
      ".EGGGE.........BBBBBBBBCBBBBBBBBBB........EGGGE.",
      ".EGGGEHHHHHH...CBBBBBBBBBBBCBBBBBH..HHHHHHEGGGE.",
      ".EGGGEHHHHHH...HHBBBBBBBBBBBBBBBHH..HHHHHHEGGGE.",
      ".EGGGEHHHHHH.HHHHHHBBBBBBBBBBBHHHHA.HHHHHHEGGGE.",
      ".EGGGEHHHHHH.HHAHAHAAHHBBBHAHAHHHHHHHHHHHHEGGGE.",
      ".EGGGEHHHHHH.HHAHHHHHHHHHHHHAHHHHHAHHHHHHHEGGGE.",
      ".EGGGE.......HAAHHHHHHHHHHAHAHHHHHHH......EGGGE.",
      ".EGGGE.......HHHHHAHHHAHHHHHHAHAHHHH......EGGGE.",
      ".EGGGE......HHHHHHHHHHHHHHHHHHHHHHHHH.....EGGGE.",
      ".EEEEE......HAHHAAHHHHHAHHHHHHAHHHHHH.....EEEEE.",
      ".EEEEE......HAHHHHHHHHHAHHAHHHAHHHHHH.....EEEEE.",
      ".............HAHHAAAHHHAHHHAHAHHHHAH............",
      ".............HAHAHAHHHAAAAHAHHAAHHHH............",
      ".............HEEEEEEEEEGGEEEEEEEEEHH............",
      ".............AEEEEEEEEEEEEEEEEEEEEAH............",
      ".............HEEEEEEEEEEEEEEEEEEEEH.............",
      ".............AHAAHHHHHHHHHHHAAHHHAA.............",
      ".............HHHHHAAHHHHHHAHHAHHHHA.............",
      ".............AAHHHHHHHHHHHHHHHHAHHH.............",
      "...............AAAHHHHHHHHHHHHHAA...............",
      "...............AAAAHHHHHHHHHHHAAA...............",
      "...............AAAAAAA.HHHAAAAAAA...............",
      "...............AAAAAAA....AAAAAAA...............",
      "...............AAAAAAA....AAAAAAA...............",
      "...............AAAAAAA....AAAAAAA...............",
      "...............AAAAAAA....AAAAAAA...............",
      "...............AAAAAAA....AAAAAAA...............",
      "...............EEEEEEE....EEEEEEE...............",
      "...............EEEEEEE....EEEEEEE...............",
      "...............EEEEEEE....EEEEEEE...............",
      "................................................"
    ], { '.':null,'A':'#3a0870','B':'#b44cff','C':'#7a20cc','D':'#d080ff','E':'#39ff14','F':'#103010','G':'#a0ff66','H':'#6a10cc' }),

    // vex
    vex: parseSprite([
      "................................................",
      "................................................",
      "................................................",
      ".......................AAA......................",
      "...................AAAAAAAAAAA..................",
      ".................AAAAAAAAAAAAAAA................",
      "................AAAABAAABAAAAAAAA...............",
      "...............BAABAABAABAAABAAAAA..............",
      "..............AAAAAAAAABABAABBBAAAA.............",
      ".............AABBACAABAAAAAABBAAABAA............",
      "............BBBBBBBBBBBBBBBBBBBBBBBB............",
      "............BBBBBBBBBBBBBBBBBBBBBBBBA...........",
      "............BBBBBBBBBBBBBBBBBBBBBBBBA...........",
      "............BBBBBBBBBBBBBBBBBBBBBBBBA...........",
      "...........ABBBBBBBBBBBBBBBBBBBBBBBBAA..........",
      "...........ABBBBBBBBBBBBBBBBBBBBBBBBAA..........",
      "...........ABBDDEEEEEEDDDDEEEEEEDDBBAA..........",
      "............BBDDEEFEEEDDDDEEFEEEDDBBA...........",
      "............BBDDEEEEEEDDDDEEEEEEDDBBA...........",
      "............BBDDDDDDDDDDDDDDDDDDDDBBA...........",
      ".........G..BBBBBBBBBBBBBBBBBBBBBBBB...G........",
      ".....GGGGGGGBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGGG....",
      "....GGGGGGGGBBBBBBGGGGGGGGGGGGBBBBBBGGGGGGGGG...",
      "....GGGGGGGGBBBBBBGGGGGGGGGGGGBBBBBBGGGGGGGGG...",
      "...GGGEEEEEEEEGBAAGGGGGGGGGGGGAAAGEEEEEEEEGGGG..",
      "....GGEEEEEEEEGBBAAAAAAAAAAAAAAABBEEEEEEEEGGG...",
      "....GGEEEEEEEEGBBBBAAAAAAAAAAABBBBEEEEEEEEGGG...",
      ".....GGGGGGGGGBDBDBDDBBAAABDBDBBBBBGGGGGGGGG....",
      "......BBBGBBBBBDBBBBBBBBBBBBDBBBBBBBBBBGBB......",
      "......BBBBBBBBDDBBBBBBBBBBDBDBBBBBBBBBBBBB......",
      "......BBBBBBBBBBBBDBBBDBBBBBBDBDBBBBBBBBBB......",
      "......BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB......",
      "......BBBBBBBBBBDDBBBBBDBBBBBBDBBBBBBBBBBB......",
      "......BBBBBBBBBBBBBBBBBDBBDBBBDBBBBBBBBBBB......",
      "......BBBBBBBBDBBDDDBBBDBBBDBDBBBBBBBBBBBB......",
      "......BBBBBBBBDBDBDBBBDDDDBDBBDDBBBBBBBBBB......",
      "......BBBBBBBBEEEEEEEEEHHEEEEEEEEEBBBBBBBB......",
      "......BBBBBBBBEEEEEEEEEEEEEEEEEEEEBBBBBBBB......",
      ".............BEEEEEEEEEEEEEEEEEEEEB.............",
      ".............DBDDBBBBBBBBBBBDDBBBDD.............",
      ".............BBBBBDDBBBBBBDBBDBBBBD.............",
      ".............DDBBBBBBBBBBBBBBBBDBBB.............",
      "...............DDDBBBBBBBBBBBBBDD...............",
      "...............DDDDBBBBBBBBBBBDDD...............",
      "...............DDDDDDD.BBBDDDDDDD...............",
      "...............DDDDDDD....DDDDDDD...............",
      "...............DDDDDDD....DDDDDDD...............",
      "...............DDDDDDD....DDDDDDD...............",
      "...............DDDDDDD....DDDDDDD...............",
      "...............DDDDDDD....DDDDDDD...............",
      "...............EEEEEEE....EEEEEEE...............",
      "...............EEEEEEE....EEEEEEE...............",
      "...............EEEEEEE....EEEEEEE...............",
      "................................................"
    ], { '.':null,'A':'#8a98a8','B':'#5a6678','C':'#c0cad4','D':'#3a4450','E':'#ffd700','F':'#402000','G':'#a8b4c0','H':'#ffe888' }),

    // nia
    nia: parseSprite([
      "................................................",
      "................................................",
      "................................................",
      ".......................AAA......................",
      "...................AAAAAAAAAAA..................",
      ".................AAAAAAAAAAAAAAA................",
      "................AAAABAAABAAAAAAAA...............",
      "...............BAABAABAABAAABAAAAA..............",
      "..............AAAAAAAAABABAABBBAAAA.............",
      ".............AABBACAABAAAAAABBAAABAA............",
      ".............AAAACACABAAAAABAAAABAAA.D..........",
      "............AAABAAAABAAABAAABBBAABAAAD..........",
      "............AAAABABAAAAAAAAAAAAAAAAAADE.........",
      "............BBBAAAAABABABBBABAABBAAAAD..........",
      "...........AAAAAABAAAAAAAAAAAAAAAAAAAD..........",
      "...........AABAAFFFFFFAAABFFFFFFBAAAADD.........",
      "...........AAAAAFFGFFFAAABFFGFFFAAAAADF.........",
      "............BAAAFFFFFFAABAFFFFFFAABAAD..........",
      "............AAAAAAABAAAAAAAAAAABABBAADEEE.......",
      "............AAABAAAABABABAABAAAABAAAAEEEE.......",
      ".............AFABAAAAABBAAAAAABAAFAA.EEEE.......",
      ".............AAABAAAAAAAAABAAAAAAAAA.EEEE.......",
      "..............AAAABBBAAABAAAAAABBAA..EEEE.......",
      "...............AAAAAAAABAAAAAAAAAA...EEEE.......",
      "...............BAAAAAAAAAAABAAAAAD...EEEE.......",
      "...............DDAAAAAAAAAAAAAAADD...EEEE.......",
      ".......DDDDDDDDDDDDAAAAAAAAAAADDDDEDDEEEE.......",
      ".......DDDDDDDDEDEDEEDDAAADEDEDDDDDDDEEEE.......",
      ".......DDDDDDDDEDDDDDDDDDDDDEDDDDDEDDEEEE.......",
      ".......DDDDDDDEEDDDDDDDDDDEDEDDDDDDDDEEEE.......",
      ".......DDDDDDDDDDDEDDDEDDDDDDEDEDDDDDEEEE.......",
      ".......DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEE.......",
      ".......DDDDDDEDDEEDDDDDEDDDDDDEDDDDDDEEEE.......",
      ".......DDDDDDEDDDDDDDDDEDDEDDDEDDDDDDEEEE.......",
      ".......DDDDDDDEDDEEEDDDEDDDEDEDDDDEDDDDDD.......",
      ".......DDDDDDDEDEDEDDDEEEEDEDDEEDDDDDDDDD.......",
      ".......DDDDDDDFFFFFFFFFHHFFFFFFFFFDDDDDDD.......",
      ".......DDDDDDEFFFFFFFFFFFFFFFFFFFFEDDDDDD.......",
      ".............DFFFFFFFFFFFFFFFFFFFFD.............",
      ".............EDEEDDDDDDDDDDDEEDDDEE.............",
      ".............DDDDDEEDDDDDDEDDEDDDDE.............",
      ".............EEDDDDDDDDDDDDDDDDEDDD.............",
      "...............EEEDDDDDDDDDDDDDEE...............",
      "...............EEEEDDDDDDDDDDDEEE...............",
      "...............EEEEEEE.DDDEEEEEEE...............",
      "...............EEEEEEE....EEEEEEE...............",
      "...............EEEEEEE....EEEEEEE...............",
      "...............EEEEEEE....EEEEEEE...............",
      "...............EEEEEEE....EEEEEEE...............",
      "...............EEEEEEE....EEEEEEE...............",
      "...............FFFFFFF....FFFFFFF...............",
      "...............FFFFFFF....FFFFFFF...............",
      "...............FFFFFFF....FFFFFFF...............",
      "................................................"
    ], { '.':null,'A':'#d0d0e0','B':'#9090a8','C':'#f0f0f8','D':'#a0a0c0','E':'#707090','F':'#ff69b4','G':'#401030','H':'#ffb0d0' }),

    // ryn
    ryn: parseSprite([
      "......................AAAAA.....................",
      "..................AAAAAAAAAAAAA.................",
      "................AAAAAAAAAAAAAAAAA...............",
      "..............AAAAAAAAAAAAAAAAAAAAA.............",
      ".............AAAAAAAAAAAAAAAAAAAAAAA............",
      "............AAAAAAAAAAABBBAAAAAAAAAAA.....C.....",
      "...........AAAAAAAABBBBBBBBBBBAAAAAAAA..CCCCC...",
      "...........AAAAAABBBBBBBBBBBBBBBAAAAAA.CCCCCCC..",
      "..........AAAAAABBBBBBBBBBBBBBBBBAAAAAACCCCCCC..",
      "..........AAAAABBBBBBBBBBBBBBBBBBBAAAAACCCDCCCC.",
      "..........AAAABBBBBBBBBBBBBBBBBBBBBAAAACCCCCCC..",
      ".........AAAABBBBBBBBBBBBBBBBBBBBBBBAAAACCCCCC..",
      ".........AAAABBBBBBBBBBBBBBBBBBBBBBBAAAACCCCC...",
      ".........AAAABBBBBBBBBBBBBBBBBBBBBBBAAAA.ECE....",
      "..........AABBBBBBBBBBBBBBBBBBBBBBBBBAA..EEE....",
      "..........AABBBBCCCCCCBBBBCCCCCCBBBBBAA..EEE....",
      "..........AABBBBCCFCCCBBBBCCFCCCBBBBBAA..EEE....",
      "...........AABBBCCCCCCBBBBCCCCCCBBBBAA...EEE....",
      "...........AABBBBBBBBBBBBBBBBBBBBBBBAA...EEE....",
      "............ABBBBBBBBBBBBBBBBBBBBBBBA....EEE....",
      ".............ABBBBBBBBBBBBBBBBBBBBBA.....EEE....",
      ".............BABBBBBBBBBBBBBBBBBBBAB.....EEE....",
      "..............BBBBBBBBBBBBBBBBBBBBB......EEE....",
      "...............BBBBBBBBBBBBBBBBBBB.......EEE....",
      "...............GBBBBBBBBBBBBBBBBBH.......EEE....",
      "...............HHBBBBBBBBBBBBBBBHH.......EEE....",
      "........HHHHHHHHHHHBBBBBBBBBBBHHHHHHHHHH.EEE....",
      "........HHHHHHHAHAHAAHHBBBHAHAHHHHHHHHHH.EEE....",
      "........HHHHHHHAHHHHHHHHHHHHAHHHHHHHHHHH.EEE....",
      "........HHHHHHAAHHHHHHHHHHAHAHHHHHHHHHHH.EEE....",
      "........HHHHHHHHHHAHHHAHHHHHHAHAHHHHHHHH.EEE....",
      "........HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.EEE....",
      "........HHHHHHHHAAHHHHHAHHHHHHAHHHHHHHHH.EEE....",
      "........HHHHHHHHHHHHHHHAHHAHHHAHHHHHHHHH.EEE....",
      "........HHHHHHAHHAAAHHHAHHHAHAHHHHHHHHHH.EEE....",
      "........HHHHHHAHAHAHHHAAAAHAHHAAHHHHHHHH.EEE....",
      "........HHHHHHCCCCCCCCCEECCCCCCCCCHHHHHH.EEE....",
      "........HHHHHHCCCCCCCCCCCCCCCCCCCCHHHHHH.EEE....",
      ".............HCCCCCCCCCCCCCCCCCCCCH......EEE....",
      ".............AHAAHHHHHHHHHHHAAHHHAA......EEE....",
      ".............HHHHHAAHHHHHHAHHAHHHHA......EEE....",
      ".............AAHHHHHHHHHHHHHHHHAHHH......EEE....",
      "...............AAAHHHHHHHHHHHHHAA........EEE....",
      "...............AAAAHHHHHHHHHHHAAA........EEE....",
      "...............AAAAAAA.HHHAAAAAAA...............",
      "...............AAAAAAA....AAAAAAA...............",
      "...............AAAAAAA....AAAAAAA...............",
      "...............AAAAAAA....AAAAAAA...............",
      "...............AAAAAAA....AAAAAAA...............",
      "...............AAAAAAA....AAAAAAA...............",
      "...............CCCCCCC....CCCCCCC...............",
      "...............CCCCCCC....CCCCCCC...............",
      "...............CCCCCCC....CCCCCCC...............",
      "................................................"
    ], { '.':null,'A':'#044858','B':'#40e8ff','C':'#ffd700','D':'#ffffff','E':'#bb8800','F':'#403000','G':'#1090a8','H':'#087888' }),

    // cat_kitten — minaccioso
    cat_kitten: parseSprite([
      "........AABB...............ABBB.........",
      "........BBBB...............BBBA.........",
      "........ABBB.....AAA.......ABBB.........",
      "........BCCB.ADDADDDADDD...ACCB.........",
      ".......ABCCDADDDAADDDDDAAA..ACBB........",
      ".......BBCCAADDADDDDDDADDDD.CCBA........",
      ".......BBCCADADDDDDDDDDDDAAACCBB........",
      ".......ABCCDDDADADDDDDAADADDCCBB........",
      "......BBBBAAAAAAADDAAAAAAAAAABBBB.......",
      "......ABBBAAAAAAADDDDDAAAAAAABBBA.......",
      "......BBBBDDAAAADDAAADADDAADDBBAA.......",
      "......ADDDAAEFGFFAHDDDEFGFFADDA.........",
      "......AADDADFFGJFHHHHJFFGFFJADD.........",
      "......AAADDDJFGAFHJHHAFFJFFADDA....A....",
      ".......AAADDAFGFFHAHHHFFAFFDDD...AA.....",
      ".......ADAKAHHHHHHHHHHHHHADKDA...AA.....",
      ".......ADAAHHHHHHHHHHHHHHHDADA...ADA....",
      "......DADDDAHHHHHHLLHHHHHAADADA..AD.....",
      "......ADADDDHHMNNMMMMMNNMDADDDD..AA.....",
      ".....ADDADDDDHMNNMMMMMNNMAAAADDD..ADA...",
      ".....ADDDDDDDDMNNPMMPMNNMDAAAADD..AD....",
      "....DDDADADDDDDNNDHDDDNNDADAADADD.AD....",
      "....DADDAADDDAAQNDDDAAQNADDADDADA.ADJ...",
      "....DADDADADAAAAJARAAAAADADDDADDA.AD....",
      ".....DDAADDAAAAAAARSSAATADAADDDD...AA...",
      ".....ADDDADDDAAAAAARASAAADDADDDA...ADJ..",
      "......DDDADDDAAAAAARAASADDAAADA....AD...",
      "......DADDDDDDAAAAAARAADDADDDAD....AA...",
      ".......DDADDDADDDDAARAAAADDDDA..........",
      ".......AAAAAADDAAAAAAADAAAAAA...........",
      ".......AAAAAADAAAAAAADAAAAAAA...........",
      ".......AAAAAAAAAAAAAADAAAAAAA...........",
      ".......AAAAAA..AAAAAA..AAAAAA...........",
      ".......AAAAAA..AAAAAA..AAAAAA...........",
      ".......AAAAAA..AAAAAA..AAAAAA...........",
      ".......AAAAAA..AAAAAA..AAAAAA...........",
      ".......AAAAUA..UAAAUA..UAAAUA...........",
      "........AN......AA......JN.............."
    ], { '.':null,'A':'#6a4010','B':'#8a5020','C':'#8a1020','D':'#b87830','E':'#fff0a0','F':'#ffcc00','G':'#1a1000','H':'#d8a050','J':'#ff4422','K':'#5a1010','L':'#8a2030','M':'#1a0505','N':'#ffffff','P':'#e8e8e8','Q':'#ddd','R':'#3a0808','S':'#4a1010','T':'#8a1010','U':'#f0f0f0' }),

    // cat_tabby — minaccioso
    cat_tabby: parseSprite([
      "........ABAB...............BBBB.........",
      "........BBBB...............BBBB.........",
      "........BBBB.....ACA.......BBBB.........",
      "........ADDB.ACACCCCCCCC...BDDB.........",
      ".......BBDDCACCCAACCCCCAAA..ADBB........",
      ".......BBDDAACCACCCCCCACCCA.ADBA........",
      ".......BBAAACAACCAACCAACCAAADDBA........",
      ".......BBAACCAACAAACCAAACAACDDBB........",
      "......BBBAAAAAAAAAAAAAAAAAAAABBBB.......",
      "......BBBBAAAAAAACCCCCAAAAAAABBBA.......",
      "......ABBBCCAAAACCAAACACCAACCBBBB.......",
      "......CCCCAAEFGFFAHCCCEFGFFACCA.........",
      "......CACCACFFGJFHHHHJFFGFFJACA.........",
      "......CAACCCJFGAFHJHHAFFJFFACCC....J....",
      ".......AAACCAFGFFHAHHHFFAFFCCC...AC.....",
      ".......CCAAAHHHHHHHHHHHHHACCCC...AA.....",
      ".......ACAAHHHHHHHHHHHHHHHCACC...ACA....",
      "......CACCCAHHHHHHKKHHHHHAACACA..AC.....",
      "......CCACCCHHLMMLLLLLMMLCACCCC..AA.....",
      ".....ACCACCCCHLMMLLLLLMMLAAAACCA..ACJ...",
      ".....ACCCCCCCCLMMNLLNLMMLCAAAACC..AA....",
      "....ACCAPPCCPPCMPPHCPPMMPPCAACACC.AA....",
      "....AACCPPCCPPAQPPCCPPQMPPCACCACC.ACJ...",
      "....CACCPPACPPAAPPRAPPAAPPCCCACCC.AC....",
      ".....CCAPPCAPPAAPPRSPPATPPAACCCC...AC...",
      ".....ACCPPCCPPAAPPARPPAAPPCACCCA...ACJ..",
      "......ACCACCCAAAAAARAASACCAAACA....AC...",
      "......CACCCCCCAAAAAARAACCACCCAC....AC...",
      ".......ACACCCACCCCAARAAAACCCCA..........",
      ".......AAAAAACCAAAAAAACAAAAAA...........",
      ".......AAAAAACAAAAAAACAAAAAAA...........",
      ".......AAAAAACAAAAAAACAAAAAAA...........",
      ".......AAAAAA..AAAAAA..AAAAAA...........",
      ".......AAAAAA..AAAAAA..AAAAAA...........",
      ".......AAAAAA..AAAAAA..AAAAAA...........",
      ".......AAAAAA..AAAAAA..AAAAAA...........",
      ".......UAAAUA..AAAAAA..UAAAUA...........",
      "........AA......JA......JM.............."
    ], { '.':null,'A':'#4a2008','B':'#6a3010','C':'#8a4a18','D':'#8a1020','E':'#ddff88','F':'#88ff00','G':'#102000','H':'#b86828','J':'#ff3300','K':'#5a1810','L':'#1a0505','M':'#ffffff','N':'#e8e8e8','P':'#3a1810','Q':'#ddd','R':'#3a0808','S':'#4a1010','T':'#8a1010','U':'#f0f0f0' }),

    // cat_hunter — minaccioso
    cat_hunter: parseSprite([
      "........AAAA...............AABB.........",
      "........AAAB...............AAAA.........",
      "........AAAA.....CBB.......AAAA.........",
      "........BDDB.CCCCCCCBCCC...ADDB.........",
      ".......AADDCBCCCBBCCCCCBBB..DDAA........",
      ".......AADDBBCCBCCCCCCBCCCC.BDAA........",
      ".......AADDBCBCCCCCCCCCCCBBCDDAB........",
      ".......AADDCCCBCBCCCCCBBCBCCDDAA........",
      "......AAAABBBBBBBCCBBBBBBBBBBAAAB.......",
      "......AAAABBBBBBBCCCCCBBBBBBBAAAA.......",
      "......AAAACCBBBBCCBBBCBCCBBCCAAAA.......",
      "......CCCCBBEFGFFBHCCCEFGFFBCCC.........",
      "......BBCCBCFFGJFHHHHJFFGFFJBCB.........",
      "......CBBCCCJFGBFHJHHBFFJFFBCCC....J....",
      ".......BBBCCBFGFFHBHHHFFBFFCCC...BC.....",
      ".......BCBBBHHHHHHHHHHHHHBCCCB...BB.....",
      ".......CCBBHHKKHHHHHHHHHKKCBCC...BCJ....",
      "......CBCCKKKHHHHHLLHHHHHBKKKCB..BB.....",
      "......CCKKCCHHMNNMMMMMNNMCBCCKK..BC.....",
      ".....BCCBCCCCHMNNMMMMMNNMBBBBCCC..BBB...",
      ".....BCCCCCCCCMNNPMMPMNNMCBBBBCC..BC....",
      "....BCCBCBCCCCCNNCHCCCNNCBCBBCBCC.BC....",
      "....CBCCBBCCCBBQNCCCBBQNBCCBCCBCC.BCJ...",
      "....CBCCBCBCBBBBJBRBBBBBCBCCCBCCC.BC....",
      ".....BCBBCCBBBBBBBRSSBBTBCBBCCCC...BB...",
      ".....BCCCBCCCBBBBBBRBSBBBCCBCCCC...BCB..",
      "......BCCBCCCBBBBBBRBBSBCCBBBCC....BB...",
      "......CBCCCCCCBBBBBBRBBCCBCCCBC....BB...",
      ".......CCBCCCBCCCCBBRBBBBCCCCC..........",
      ".......BBBBBBCCBBBBBBBCBBBBBB...........",
      ".......BBBBBBCBBBBBBBCBBBBBBB...........",
      ".......BBBBBBCBBBBBBBCBBBBBBB...........",
      ".......BBBBBB..BBBBBB..BBBBBB...........",
      ".......BBBBBB..BBBBBB..BBBBBB...........",
      ".......BBBBBB..BBBBBB..BBBBBB...........",
      "......BNBBBBB..BBBBBB..BBBBBNN..........",
      "......NNBBBBB..UBBBUB..UBBBBNB..........",
      "......NBBN......JB......JN..NN.........."
    ], { '.':null,'A':'#5a2008','B':'#3a1800','C':'#7a3810','D':'#8a1020','E':'#ff8866','F':'#ff1100','G':'#200000','H':'#a05020','J':'#ff6600','K':'#2a0808','L':'#4a0800','M':'#1a0505','N':'#ffffff','P':'#e8e8e8','Q':'#ddd','R':'#3a0808','S':'#4a1010','T':'#8a1010','U':'#f0f0f0' }),

    // cat_archer — minaccioso
    cat_archer: parseSprite([
      "........AAAA...............BABA.........",
      "........AAAB...............AAAA.........",
      "........AAAA.....CCB.......AAAA.........",
      "........BDDA.CBBCCCCCCBB...BDDB.........",
      ".......AADDCBCCCBBCCCCCBBB..DDAA........",
      ".......AADDBBCCBCCCCCCBCCCC.DDAA........",
      ".......AADDBCBCCCCCCCCCCCBBCDDAA........",
      ".......BADDCCCBCBCCCCCBBCBCCDDAA........",
      "......AAAABBBBBBBCCBBBBBBBBBBAAAE.......",
      "......AAAABBBBBBBCCCCCBBBBBBBAAAFB......",
      "......BAAACCBBBBCCBBBCBCCBBCCAABFE......",
      "......BCCCBBGHJHHBKCCCGHJHHBCCC.B.E.....",
      "......BBCCBCHHJLHKKKKLHHJHHLBCB.F.B.....",
      "....M.BBBCCCLHJBHKLKKBHHLHHBCCC.F..E....",
      "...NNN.BBBCCBHJHHKBKKKHHBHHCCC..FBCE....",
      "...NNN.BCBBBKKKKKKKKKKKKKBCCCC..FBC.E...",
      "...NNB.CCBBKKKKKKKKKKKKKKKCBCB..BBCBE...",
      "...NNNCBCCCBKKKKKKPPKKKKKBBCBCB.FBC..B..",
      "...NNNCCBCCCKKQRRQQQQQRRQCBCCCC.FBC.E...",
      "...NNNCCBCCCCKQRRQQQQQRRQBBBBCCCB.BBE...",
      "...BNNCCCCCCCCQRRSQQSQRRQCBBBBCCF.BB....",
      "...BNNCBCBCCCCCRRCKCCCRRCBCBBCBCB.BB....",
      "...BNNCCBBCCCBBTRCCCBBTRBCCBCCBCB.ECB...",
      "...NNNCCBCBCBBBBLBUBBBBBCBCCCBCCB.BC....",
      "...NNNCBBCCBBBBBBBUVVBBWBCBBCCCCFB.BC...",
      "...NNNCCCBCCCBBBBBBUBVBBBCCBCCCBFB.BCB..",
      "......CCCBCCCBBBBBBUBBVBCCBBBCC.B..BB...",
      "......CBCCCCCCBBBBBBUBBCCBCCCBB....BC...",
      ".......BCBCCCBCCCCBBUBBBBCCCCC..........",
      ".......BBBBBBCCBBBBBBBCBBBBBB...........",
      ".......BBBBBBCBBBBBBBCBBBBBBB...........",
      ".......BBBBBBCBBBBBBBCBBBBBBB...........",
      ".......BBBBBB..BBBBBB..BBBBBB...........",
      ".......BBBBBB..BBBBBB..BBBBBB...........",
      ".......BBBBBB..BBBBBB..BBBBBB...........",
      ".......BBBBBB..BBBBBB..BBBBBB...........",
      ".......BBBBXB..BBBBXB..BBBBBB...........",
      "........BR......BR......LB.............."
    ], { '.':null,'A':'#6a4020','B':'#4a3010','C':'#8a6030','D':'#8a1020','E':'#6a3020','F':'#4a2010','G':'#ccff88','H':'#66ff22','J':'#102000','K':'#b88848','L':'#ff4400','M':'#ff4422','N':'#3a2010','P':'#5a2810','Q':'#1a0505','R':'#ffffff','S':'#e8e8e8','T':'#ddd','U':'#3a0808','V':'#4a1010','W':'#8a1010','X':'#f0f0f0' }),

    // cat_werewolf — minaccioso
    cat_werewolf: parseSprite([
      "........AAAB..BBB...BBB....AABA.........",
      "........AABA.BBBBB.BBBBB..BAAAA.........",
      "........ABBB..BBBCCCBBB..BBBAAB.........",
      "........BBBBBBCBCCCCCBCBBBBBBDA.........",
      ".......BABBBBCCCBBCCCCCBBBBBDDAB........",
      "......BAADBBBCCBCCCCCCBCCCB.DDBA........",
      ".....BBBADDBCBCCCCCCCCCCCBBBDBBB........",
      "....BBBBBDDCCCBCBCCCCCBBCBCCBBBBB.......",
      ".....BBBAABBBBBBBCCBBBBBBBBBBBBBA.......",
      ".....BBAAABBBBBBBCCCCCBBBBBBBABBA.......",
      "....BBBAAACCBBBBCCBBBCBCCBBCCABBB.......",
      "...BBBBBCCBBEFGFFBHCCCEFGFFBCBBBBB......",
      "....BBBBCCBCFFGJFHHHHJFFGFFJBCBBB.......",
      ".....BBBBCCCJFGBFHJHHBFFJFFBCCBB...J....",
      ".....BBBBBCCBFGFFHBHHHFFBFFCCBBB.BB.....",
      "....BBBBBBBBHHHHHHHHHHHHHBCCBBBBBBC.....",
      ".....BBBCBBHHHHHHHHHHHHHHHCBCBBB.BCB....",
      "......BBCCBBHHHHHHKKHHHHHBBCBCB..BC.....",
      "......CCBBBBHHLMMMLLLMMMLBBBCCC..BC.....",
      ".....BCCBBBBBHLBMMLLLMMMBBBBBCCC..BCB...",
      ".....BCCCBBBCCBBBMLLBMBMLBBBBBCB..BC....",
      "....CCCBCBBCCBBBBMHBBMBBCBBBBCBCB.BC....",
      "....CBCCBBCCCBBBBCCCBBBMBCCBCCBCC.BCJ...",
      "....CBCCBCBCBBBBJBNBBBBBCBCCCBCCC.BC....",
      ".....CCBBCCBBBBBBBNPPBBQBCBBCCCC...BB...",
      ".....BCCCBCCCBBBBBBNBPBBBCCBCCCB...BCJ..",
      "......BCCBCCCBBBBBBNBBPBCCBBBCB....BC...",
      "......CBCCCCCCBBBBBBNBBCCBCCCBB....BB...",
      ".......BCBCCCBCCCCBBNBBBBCCCCC..........",
      ".......BBBBBBCCBBBBBBBCBBBBBB...........",
      ".......BBBBBBCBBBBBBBCBBBBBBB...........",
      ".......BBBBBBCBBBBBBBBBBBBBBB...........",
      ".......BBBBBB..BBBBBB..BBBBBB...........",
      ".......BBBBBB..BBBBBB..BBBBBB...........",
      ".......BBBBBB..BBBBBB..BBBBBB...........",
      ".......BBBBBB..BBBBBB..BBBBBB...........",
      ".......RBBBBB..RBBBRB..BBBBBB...........",
      "........BM......JM......JB.............."
    ], { '.':null,'A':'#4a1000','B':'#2a0a00','C':'#6a2208','D':'#8a1020','E':'#ff6666','F':'#ff0000','G':'#1a0000','H':'#8a3818','J':'#ff2200','K':'#300000','L':'#1a0505','M':'#ffffff','N':'#3a0808','P':'#4a1010','Q':'#8a1010','R':'#f0f0f0' }),

    // cat_shadow — minaccioso
    cat_shadow: parseSprite([
      "........ABCB...............ACAC.........",
      "........CBBC...............CAAA.........",
      "........BAAA.....DDD.......CABA.........",
      "........CEEA.DBBBBDBDCCD...CEEC.........",
      ".......AAEEDBDBDCCDDDDDBCC..EEAC........",
      ".......CABBCCBDCDDBDDDCDDDC.EEAA........",
      ".......AAEECDCDDDBDDBDDDDCCDBEAC........",
      ".......CAEEDDDCDCBDDDDCCBCBDBEAA........",
      "......AAABCCCBCCCDDCCCCCCCCBCAAAA.......",
      "......AAAABCCCCCBDDDBDCCBCCCCAAAB.......",
      "......CAAADBCCCCDDCCCDCDDCCDDBBAA.......",
      "......DDDDCCBFGFFCBDDBHFGFFCDDC.........",
      "......DCBDCDFFGJFBKKKJFFGFFJCDD...D.....",
      "......BCBDDDJFGCBKJKKCFFJFFCDBC...DJ....",
      ".......CCCDDCFBBBBCBKBFFBBFDDD...CC.....",
      ".......DDCCCBKBKKKKKKKKBKCDDDC...CD.....",
      ".......DDBBKKBKKKKBKKKKKKKDCDC...CDJ....",
      "......DCDDDCKKKKKBLLBKKKKCCDBDC..CD.....",
      "......DDCDDDKKMNNBMMMMNNBDBDBDD..CD.....",
      ".....CDDCBDDDBMNNMMMMMNNMCCBCDDD..DBB...",
      ".....CDDDDBDDDMNBPMMBMNNBDCCCCDC..BD....",
      "....DDDCDCDBDDDNNDKDDDNNDCDCCBBDD.CD....",
      "....CCDDCCDDBCCQNDBDCBQNCDDCDDCDC.CDJ...",
      "....CCDDBDCDCCCCJBRCCCCCDCDDDCDDD.CC....",
      ".....DBCBDDCCCCCBCRSSCCTCDCCDBDD...CD...",
      ".....CDBDCDDDCBBBBCBCBCCBBDCDDBD...CBJ..",
      "......DDDCDDBCBCCCCRCCSBDDCCCDD....CD...",
      "......DCDBBDDBCCCCBCRCCDDCDDDCD....CD...",
      ".......DDCDDDCDDDBCCBCCCCDDDBC..........",
      ".......CCCCCCDDCCBCCCCDCBCBCB...........",
      ".......CCBCCCBCCCCCCCDCCCCCBC...........",
      ".......CCCBCCDCCBCCCBDCCBCCCC...........",
      ".......CCCCBC..CCCCCC..CCCCCC...........",
      ".......CCCCCB..CCCBCC..CCCCCC...........",
      ".......CBCCCC..CCBCCC..CCCCCC...........",
      ".......CBCCCC..CBCCCC..CCCCCC...........",
      ".......BCCCCC..BBBCBC..CBBCCC...........",
      "........CN......CN......CN.............."
    ], { '.':null,'A':'#180828','B':'#1a0828','C':'#100818','D':'#2a1040','E':'#8a1020','F':'#ff44ff','G':'#220033','H':'#ff99ff','J':'#aa22ff','K':'#3a2060','L':'#661188','M':'#1a0505','N':'#ffffff','P':'#e8e8e8','Q':'#ddd','R':'#3a0808','S':'#4a1010','T':'#8a1010' }),

    // cat_boss — minaccioso
    cat_boss: parseSprite([
      "..........AAAABCDCBBCDCBBCDCBBCDCBBCDCAAAAA.........",
      "..........AAAABCCCBBCCCBBCCCBBCCCBBCCCAAAAA.........",
      "..........AAAABCCCBBECCBBCCCBBCCEBBCCCAAAAA.........",
      ".........AAFFABBBBBBCCCBBBBBBBCCCBBBBBAFFAAA........",
      ".......G.AAFFABBBBBBBBBBBBBBBBBBBBBBBBAFFAAA.G......",
      "......GGAAAFFAAAHHHHHHHHHHHHHHHHHHHHHAAFFAAAGGG.....",
      ".....GGGAAAFFAAHHHHHHHHHHHHHHHHHHHHHHHAFFAAAAGGG....",
      "......GGAAAFFAHHHHHHHHHHHHHHHHHHHHHHHHHFFAAAAGG.....",
      ".....AAGAAAFFHHHHHHHHHHHHHHHHHHHHHHHHHHFFAAAAAAA....",
      ".....AAAAAAAAHAAAAAAAAAHHHHHHAAAAAAAAAHHAAAAAAAA....",
      "....AAAAAAAAHHAAAAAAAAAHHHHHHAAAAAAAAAHHHAAAAAAAA...",
      "....AAAAAAAAHHAAAAAAAAAHHHHHHAAAAAAAAAHHHAAAAAAAA...",
      "...AAAAAAAAAHHHHJEEKKEEHHHHHHJEEKKEEHHHHHAAAAAAAAA..",
      "...GAAAAAAAHHHHHEEEKKEEHHHHHHEEEKKEEHHHHHHAAAAAAAG..",
      "..GGAAAAAAAHHHHHEEEKKEEHHHHHHEEEKKEEHHHHHHAAAAAAAGG.",
      "...GGAAAAA.LHHHHEEEKKEEHHMMMHEEEKKEEHHHHLH.AAAAAGG..",
      "..AAGAAAAAL.HHHHEEEKKEMMMMMMMMMEKKEEHHHHHLAAAAAAGAA.",
      "...AAAAAAL..HHHHEEEKMMMMMMMMMMMMMKEEHHHHH.LAAAAAAA..",
      "...AAAAALAA.HHHHHHHMMMMMMNNMMMMMMMHHHHHHH.ALAAAAAA..",
      "....AAAAAAAHAHHHHHHDDDMMMMMMMMDDDMHHHHHHHAAAAAAAA...",
      "...AAAAAAAAHAHHHHHPDDDPDDPPDDPDDDPMHHHHHHHHAAGAAAA..",
      "....AAAAAHHHHHHHHHPDDDPDDPPDDPDDDPHHHHHHAHAHGGGAA...",
      "....AAAAAHAAAAHHHHPDDDPDDPPDDPDDDPHHHHAHAAHAGGGGA...",
      ".....AAAAHHAHHHHHHPDDDPDDPPDDPDDDPHHHAAAAHHAGGGA....",
      "......AAAHHAHAHHAHPDDDPDDPPDDPDDDPHQHAHHAHHAAGA.....",
      "......AAHHAAHAHHHAADDDHDDMMDDHDDDAAHQHAHAHAAHAA.....",
      ".......AAAHHAAHAAAADDDAAHHHHHADDDAAHQHHAAAAHHA......",
      "........AHHHHHHHHHAARQAAAAAAAAAAAAAHAQHHHAAAH.......",
      ".........HHHHAHHAAAAAAQAAAAAAAARAAAAAHQHAHAA........",
      ".........HAAHAHHHHAAAAAQAAAAAAAAAAAHHAAHHHHH........",
      ".........HHHAAHAAAAAAAAAQAAAAAAAAAAHAAAHHAHH........",
      ".........AAHHHHHAHAAAAAAAAAAAAAAAAHHHHAHHHAA........",
      "..........HHHAAHHHHAAAAAAAAAAAAAAHAAAHHHHHA.........",
      "...........HAHAHHHAHAAAAAAAAAAAAAHAHHAHHAH..........",
      "............HHHAHAHAHAHHHAAAHHAAHAHHHAAAH...........",
      "............AHAAHHHHHAHHAHHHHAHHAAHAHHHHA...........",
      "..............HAAHHAAAAAAHHAHHAAHHHAAHH.............",
      "...........AAAAAAAAHHHAAAAAAAAAHHAAAAAAAA...........",
      "...........AAAAAAAAHHHAAAAAAAAHHHAAAAAAAA...........",
      "...........AAAAAAAAHHHAAAAAAAAHHHAAAAAAAA...........",
      "...........AAAAAAAA...AAAAAAAA...AAAAAAAA...........",
      "...........AAAAAAAA...AAAAAAAA...AAAAAAAA...........",
      "...........AAAAAAAA...AAAAAAAA...AAAAAAAA...........",
      "...........AAAAAAAA...AAAAAAAA...AAAAAAAA...........",
      "...........AAAAAAAA...AAAAAAAA...AAAAAAAA...........",
      "...........AAAAAAAA...AAAAAAAA...AAAAAAAA...........",
      "...........DAAAAASA...DAAAAASA...DAAAAASA...........",
      ".............ED.........ED.........ED..............."
    ], { '.':null,'A':'#3a0800','B':'#ffd700','C':'#ffaa00','D':'#ffffff','E':'#ff2200','F':'#8a1020','G':'#5a1000','H':'#7a1808','J':'#ffaa88','K':'#1a0000','L':'#2a0800','M':'#a02810','N':'#660000','P':'#140000','Q':'#2a0500','R':'#8a1010','S':'#ffd0d0' }),

    // tile_training
    tile_training: parseSprite([
      "ABABABABABABABABABABABAA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBAAAAAAAAAAAAAAAAAABBB",
      "ABBAAAAAAAAAAAAAAAAAABBA",
      "BBBAAAAAAAAAAAAAAAAAABBB",
      "ABBAAABBBBBBBBBBBBAAABBA",
      "BBBAAABBBBBBBBBBBBAAABBB",
      "ABBAAABBBBBBBBBBBBAAABBA",
      "BBBAAABBBBBBBBBBBBAAABBB",
      "ABBAAABBBBBBBBBBBBAAABBA",
      "BBBAAABBBBBCBBBBBBAAABBB",
      "ABBAAABBBBBDCBBBBBAAABBA",
      "BBBAAABBBBBBBBBBBBAAABBB",
      "ABBAAABBBBBBBBBBBBAAABBA",
      "BBBAAABBBBBBBBBBBBAAABBB",
      "ABBAAABBBBBBBBBBBBAAABBA",
      "BBBAAABBBBBBBBBBBBAAABBB",
      "ABBAAAAAAAAAAAAAAAAAABBA",
      "BBBAAAAAAAAAAAAAAAAAABBB",
      "ABBAAAAAAAAAAAAAAAAAABBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "ABABABABABABABABABABABAB"
    ], { '.':null,'A':'#0d1b2a','B':'#152238','C':'#00f5ff','D':'#ffffff' }),

    // tile_alien_city
    tile_alien_city: parseSprite([
      "ABABABABABABABABABABABAA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBAAAAAAAABBBBBBBBBBBBB",
      "ABBAAAAAAAABBBBBBBBBBBBA",
      "BBBAACAAAAABBBBBBBBBBBBB",
      "ABBAAAAAAAABBBBBBBBBBBBA",
      "BBBAAAAAAAABBBBBBBBBBBBB",
      "ABBAAAAAAAABBBBBBBBBBBBA",
      "BBBAAAAAAAABBBBBBBBBBBBB",
      "ABBAAAAAAAABBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "CCDCCCDCCCDCCCDCCCDCCCCC",
      "BBBBBBBBBBBBBAAAAAAAABBB",
      "ABBBBBBBBBBBBAAAAAAAABBA",
      "BBBBBBBBBBBBBAACAAAAABBB",
      "ABBBBBBBBBBBBAAAAAAAABBA",
      "BBBBBBBBBBBBBAAAAAAAABBB",
      "ABBBBBBBBBBBBAAAAAAAABBA",
      "BBBBBBBBBBBBBAAAAAAAABBB",
      "ABBBBBBBBBBBBAAAAAAAABBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "ABABABABABABABABABABABAB"
    ], { '.':null,'A':'#1a0a2e','B':'#1e1040','C':'#b026ff','D':'#ffffff' }),

    // tile_forest
    tile_forest: parseSprite([
      "ABABABABABABABABABABABAA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBCBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBCBBAAABBBBBBBBBBBBBBBB",
      "ABBBBAAABBBBBBBBBCBBBBBA",
      "BBBBBAAABBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBCDBBBBA",
      "BBBBBBBBBBBBCBBBBBBBBBBB",
      "ABBBBBBCBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBCBBBBBBBBBBBBBBBA",
      "BBCBBBBBBBBBBBAAABBBBBBB",
      "ABBBBBBBBBBBBBAAABBBBBBA",
      "BBBBBBBBBBBBBBAAABBBBBBB",
      "ABBBBBBBDBBBBBBBBCBBBBBA",
      "BBBBBBBBBBBBCBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBCBBBBBBBBBBB",
      "ABBBBBBCBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "ABABABABABABABABABABABAB"
    ], { '.':null,'A':'#0a1f0a','B':'#0f2a12','C':'#39ff14','D':'#2a6a20' }),

    // tile_temple
    tile_temple: parseSprite([
      "ABABABABABABABABABABABAA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABAAAAAAAAAAAAAAAAAAAABA",
      "BBAAAAAAAAAAAAAAAAAAAABB",
      "ABAAAAAAAAAAAAAAAAAAAABA",
      "BBAAABBBBBBBBBBBBBBAAABB",
      "ABAAABBBBBBBBBBBBBBAAABA",
      "BBAAABBBBBBBBBBBBBBAAABB",
      "ABAAABBBBBBBBBBBBBBAAABA",
      "BBAAABBBBBBBBBBBBBBAAABB",
      "ABAAABBBBBCCCCBBBBBAAABA",
      "BBAAABBBBBCDCCBBBBBAAABB",
      "ABAAABBBBBCCCCBBBBBAAABA",
      "BBAAABBBBBCCCCBBBBBAAABB",
      "ABAAABBBBBBBBBBBBBBAAABA",
      "BBAAABBBBBBBBBBBBBBAAABB",
      "ABAAABBBBBBBBBBBBBBAAABA",
      "BBAAABBBBBBBBBBBBBBAAABB",
      "ABAAABBBBBBBBBBBBBBAAABA",
      "BBAAAAAAAAAAAAAAAAAAAABB",
      "ABAAAAAAAAAAAAAAAAAAAABA",
      "BBAAAAAAAAAAAAAAAAAAAABB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "ABABABABABABABABABABABAB"
    ], { '.':null,'A':'#2a1a0a','B':'#3a2818','C':'#ffd700','D':'#ffffff' }),

    // tile_underworld
    tile_underworld: parseSprite([
      "ABABABABABABABABABABABAA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBAAAAAAAAAABBBBBBA",
      "BBBBBBBAAAAAAAAAABBBBBBB",
      "ABBBBBBAAAAAAAAAABBBBBBA",
      "BBBBBBBAAAAAAAAAABBBBBBB",
      "ABBBBBBAAAAAAAAAABBBBBBA",
      "BBBBBBBAAAAAAAAAABBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABCBBCBBCBBCBBCBBCBBCBBC",
      "BBBDBBDBBDBBDBBDBBDBBDBB",
      "ABBBEBBEBBEBBEBBEBBEBBEA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "ABABABABABABABABABABABAB"
    ], { '.':null,'A':'#1a0a0a','B':'#2a1010','C':'#ff4466','D':'#ff6622','E':'#ffaa44' }),

    // tile_star_temple
    tile_star_temple: parseSprite([
      "ABABABABABABABABABABABAA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABAAAAAAAAAAAAAAAAAAAABA",
      "BBAAAAAAAAAAAAAAAAAAAABB",
      "ABAAAAAAAAAAAAAAAAAAAABA",
      "BBAAABBBBBBBBBBBBBBAAABB",
      "ABAAABBBBBBBBBBBBBBAAABA",
      "BBAAABBBBBBBBBBBBBBAAABB",
      "ABAAABBBBBBBBBBBBBBAAABA",
      "BBAAABBBBBBBBBBBBBBAAABB",
      "ABAAABBBBBCCCCBBBBBAAABA",
      "BBAAABBBBBCDCCBBBBBAAABB",
      "ABAAABBBBBCCCCBBBBBAAABA",
      "BBAAABBBBBCCCCBBBBBAAABB",
      "ABAAABBBBBBBBBBBBBBAAABA",
      "BBAAABBBBBBBBBBBBBBAAABB",
      "ABAAABBBBBBBBBBBBBBAAABA",
      "BBAAABBBBBBBBBBBBBBAAABB",
      "ABAAABBBBBBBBBBBBBBAAABA",
      "BBAAAAAAAAAAAAAAAAAAAABB",
      "ABAAAAAAAAAAAAAAAAAAAABA",
      "BBAAAAAAAAAAAAAAAAAAAABB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "ABABABABABABABABABABABAB"
    ], { '.':null,'A':'#0a0a2a','B':'#12124a','C':'#7b68ee','D':'#ffffff' }),

    // tile_moon
    tile_moon: parseSprite([
      "ABABABABABABABABABABABAA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBABBBBBBBBBBBBBBBB",
      "ABBBBAAAAABBCBBBBBBBBBBA",
      "BBBBAAAAAAABBBBBBBBBBBBB",
      "ABBBAAAAAAABBBBBBBBBBBBA",
      "BBBAAAAAAAAABBBBBBBBBBBB",
      "ABBBAAAAAAABBBBBBBBBDBBA",
      "BBBBAAAAAAABBBBBBBBBBBBB",
      "ABBBBAAAAABBBBBBBBBBBBBA",
      "BBBBBBBABBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBABBBBBBA",
      "BBBBBBBBBBBBBBAAAAABBBBB",
      "ABBBBBBBBBBBBBAAAAABBBBA",
      "BBBBBBBBBBBBBAAAAAAABBBB",
      "ABBBBBBBBBBBBBAAAAABBBBA",
      "BBBBBBBBBBBBBBAAAAABBBBB",
      "ABBBBBBBBBBBBBBBABBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "ABABABABABABABABABABABAB"
    ], { '.':null,'A':'#1a1a2a','B':'#3a3a4a','C':'#ff6347','D':'#ffffff' }),

    // tile_cursed_city
    tile_cursed_city: parseSprite([
      "ABABABABABABABABABABABAA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBAAAAAAAABBBBBBBBBBBBB",
      "ABBAAAAAAAABBBBBBBBBBBBA",
      "BBBAACAAAAABBBBBBBBBBBBB",
      "ABBAAAAAAAABBBBBBBBBBBBA",
      "BBBAAAAAAAABBBBBBBBBBBBB",
      "ABBAAAAAAAABBBBBBBBBBBBA",
      "BBBAAAAAAAABBBBBBBBBBBBB",
      "ABBAAAAAAAABBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "CCDCCCDCCCDCCCDCCCDCCCCC",
      "BBBBBBBBBBBBBAAAAAAAABBB",
      "ABBBBBBBBBBBBAAAAAAAABBA",
      "BBBBBBBBBBBBBAACAAAAABBB",
      "ABBBBBBBBBBBBAAAAAAAABBA",
      "BBBBBBBBBBBBBAAAAAAAABBB",
      "ABBBBBBBBBBBBAAAAAAAABBA",
      "BBBBBBBBBBBBBAAAAAAAABBB",
      "ABBBBBBBBBBBBAAAAAAAABBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "ABABABABABABABABABABABAB"
    ], { '.':null,'A':'#1a0a1a','B':'#2a1530','C':'#9400d3','D':'#ffffff' }),

    // tile_star_refuge
    tile_star_refuge: parseSprite([
      "ABABABABABABABABABABABAA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBCDBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBCDBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBCBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABCCCCCCCCCCCCCCCCCCCCCA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "ABABABABABABABABABABABAB"
    ], { '.':null,'A':'#0a1a2a','B':'#102840','C':'#ff8c00','D':'#ffffff' }),

    // tile_final
    tile_final: parseSprite([
      "ABABABABABABABABABABABAA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBAAAAAAAAAABBBBBBA",
      "BBBBBBBAAAAAAAAAABBBBBBB",
      "ABBBBBBAAAAAAAAAABBBBBBA",
      "BBBBBBBAAAAAAAAAABBBBBBB",
      "ABBBBBBAAAAAAAAAABBBBBBA",
      "BBBBBBBAAAAAAAAAABBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABCBBCBBCBBCBBCBBCBBCBBC",
      "BBBDBBDBBDBBDBBDBBDBBDBB",
      "ABBBEBBEBBEBBEBBEBBEBBEA",
      "BBBBBBBBBBBBBBBBBBBBBBBB",
      "ABBBBBBBBBBBBBBBBBBBBBBA",
      "ABABABABABABABABABABABAB"
    ], { '.':null,'A':'#0a0a1a','B':'#2a2a35','C':'#ff2200','D':'#ff6622','E':'#ffaa44' }),

    // decor_tree0
    decor_tree0: parseSprite([
      "................................",
      "................................",
      "................................",
      "................................",
      "...............AAA..............",
      "...........AAAAAAAAAAA..........",
      ".........AABAABAAAAAAAAA........",
      "........AAAAAAAAAAAAAAABB.......",
      ".......AAAAABAAAAAAAABBAAA......",
      "......AAAAAAAAAAAAAAAAAAAAA.....",
      ".....ABAAABABBABAAAAAAAABAAA....",
      ".....BBAAABAABAAAAAAAAAAAAAB....",
      "....AABABACBAABAAAAAAABAAABAA...",
      "....AAAAAAAAABAABAABBAAAAAAAA...",
      "....BAAAAAAABAAAAAAACAAABAAAA...",
      "...AAAAAAABABAAABAABAAAAAAAAAA..",
      "...AAAAAAABAAAAAAAAABAAAAAAAAA..",
      "...BAAAAAAAABAAAAAAABABBBAAABA..",
      "...AABAAAAAAAABABAAAABBABABAAA..",
      "...AAAAABAAAABABBAABAAAAAAAAAA..",
      "..AAAAAABAAAABABABAAAAABAAAAAAA.",
      "...ABBBAAAAAAABABAAAAAAABABAAA..",
      "...AAAAAAAAAAAAAAAAAAABAAABAAA..",
      "...AAAAAABAAAABAAAAAAAAAAABAAA..",
      "....AAAAABBAABAAABAAAAABAAAAA...",
      ".....AAAABAAAAAAAAAABAABAABB....",
      "......ABAAAAAABAAAAABAAAABA.....",
      ".........ABBAAAABAAAAAAA........",
      "..............DBAAD.............",
      "..............BBEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD............."
    ], { '.':null,'A':'#0a4a14','B':'#063810','C':'#5dff6a','D':'#4a2a10','E':'#6a3a18' }),

    // decor_tree1
    decor_tree1: parseSprite([
      "................................",
      "................................",
      "................................",
      "................................",
      "...............AAA..............",
      "...........AAAAAAAAAAA..........",
      ".........AAAAAAAAAAAAAAA........",
      "........ABAAABAAAAAAAABAB.......",
      ".......ABAABAAABAAAAAAAAAA......",
      "......AABABAABBBAAAABAAABBA.....",
      ".....AAAAAABBAAABAAAAAAAAAAA....",
      ".....AAABAAAABAAAAAABAAAABAA....",
      "....AAABBBCABBAAAAABABAAAAAAA...",
      "....AAAAAAAAABBBAAAAABABABBBA...",
      "....AABBAAAAAAAABAAACAAAAAAAA...",
      "...AAAAAAABAAABAAAAAAABAAABAAA..",
      "...BAAAAAAAAAAAABAAABAAAABAAAA..",
      "...AABAAAAAAAAAAABABAAAAAAABAA..",
      "...AAAAAAABAAAAAAAAAAABABBAAAA..",
      "...ABAAAABABABAABAAAABAAAAAAAA..",
      "..ABAAAAABBAAAAAABAAAAAABAABAAA.",
      "...AAAAAAAABAAAAAAAAAAAAAAABBA..",
      "...BAAABAAAAAABBAAAAAAABAAAAAA..",
      "...ABAAAAAAAAAAAAAAABAAAAAAAAA..",
      "....AABAAAAAAAAAABAAAAAAAAAAA...",
      ".....AAAABABAABAAABAAAAAABAA....",
      "......AAAAABBBBAAABAAAABBBA.....",
      ".........BAAAAAAAAAAABAA........",
      "..............DABAD.............",
      "..............BEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD............."
    ], { '.':null,'A':'#0d5a1a','B':'#063810','C':'#5dff6a','D':'#4a2a10','E':'#6a3a18' }),

    // decor_tree2
    decor_tree2: parseSprite([
      "................................",
      "................................",
      "................................",
      "................................",
      "...............AAA..............",
      "...........AAAAAAAAAAA..........",
      ".........AABBABABAAAABAA........",
      "........AAABAABAAAAAAAAAA.......",
      ".......ABAAAAAAABAAAAAAAAA......",
      "......AAAAAAAAAAAAAAABBBAAB.....",
      ".....AAABAAAAABAAAAABAAABABA....",
      ".....ABAAAAAAAABAAAAABAAAAAA....",
      "....AAABABCAAABAAABBABAAABABA...",
      "....ABBBBBAAABAAAAAAAABAAAAAA...",
      "....AAAABABAAABBAAAACAAAAAAAA...",
      "...AABAAAAAAAABAAAABAABABAABAA..",
      "...AABAAABABBAAAABBAAAABAAABAA..",
      "...AAAAABBABAAAAABBAAAAAAAAABA..",
      "...AAAAAAAABBBAABAAAAAABAABAAA..",
      "...AABABAAAAABAAAAAAAAAABAAAAA..",
      "..AABAAAAABAAAABAABAAABABBBBAAA.",
      "...AAAAAAAAAAAAABAAAAAAABAAAAA..",
      "...AAAAAABAAAAAAAAAAAAAABABABA..",
      "...AAAAAAAAAABABBABAAABAAAAAAA..",
      "....BAAABAAAAAAABAAAAAAAAAAAA...",
      ".....AAAAAAAABAAAABAAAAABAAB....",
      "......AAAAABBAABAAAABAAAABB.....",
      ".........AAAAAAAAAABAAAA........",
      "..............DAAAD.............",
      "..............DEBDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD.............",
      "..............DEEDD............."
    ], { '.':null,'A':'#1a6a28','B':'#063810','C':'#5dff6a','D':'#4a2a10','E':'#6a3a18' }),

    // decor_mushroom
    decor_mushroom: parseSprite([
      "................",
      "................",
      "................",
      "........A.......",
      "....AAAAAAAAA...",
      "...AAAAAABAAAA..",
      "..AAABAAAAAAAAA.",
      "..AAAAAAAAABAAA.",
      ".AAAAAAAAAAAAAAA",
      "..AAAAAAAAAAAAA.",
      "..AAAAAAAAAAAAA.",
      "...AAAAAAAAAAA..",
      "....AAAAAAAAA...",
      ".......CAC......",
      ".......CCC......",
      ".......CCC......",
      ".......CCC......",
      ".......CCC......"
    ], { '.':null,'A':'#c03050','B':'#ffffff','C':'#e8d8b0' }),

    // decor_crystal
    decor_crystal: parseSprite([
      "................",
      "........A.......",
      "....AAAAAAAAA...",
      "....AAAAAAAAA...",
      "....AAAAAAAAA...",
      "....AAAAAAAAA...",
      "....AAAABAAAA...",
      "....AAAAAAAAA...",
      "....AAAAAAAAA...",
      "....AAAAAAAAA...",
      "....CCCCCCCCC...",
      "....CCCCCCCCC...",
      "....CCCCCCCCC...",
      "....CCCCCCCCC...",
      "....CCCCCCCCC...",
      "....CCCCCCCCC...",
      ".....CCCCCCC....",
      ".....CCCCCCC....",
      ".....CCCCCCC....",
      "......CCCCC.....",
      "......CCCCC.....",
      "......CCCCC.....",
      ".......CCC......",
      ".......CCC......",
      "................",
      "................",
      "................",
      "................"
    ], { '.':null,'A':'#88ffff','B':'#ffffff','C':'#00f5ff' }),

    // decor_pillar
    decor_pillar: parseSprite([
      "..AAAAAAAAAAAAAAAA..",
      "..AAAAAAAAAAAAAAAA..",
      "..AAAAAAAAAAAAAAAA..",
      ".BBBBBBBBBBBBBBBBBB.",
      ".BBBBBBBBBBBBBBBBBB.",
      ".BBBBBBBBBBBBBBBBBB.",
      ".BBBBBBBBBBBBBBBBBB.",
      ".BBBBBBBBBBBBBBBBBB.",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".....CDDDCCCCCC.....",
      ".BBBBBBBBBBBBBBBBBB.",
      ".BBBBBBBBBBBBBBBBBB.",
      ".BBBBBBBBBBBBBBBBBB.",
      ".BBBBBBBBBBBBBBBBBB.",
      ".BBBBBBBBBBBBBBBBBB.",
      "....................",
      "....................",
      "...................."
    ], { '.':null,'A':'#d4b840','B':'#ffd700','C':'#6a5840','D':'#8a7860' }),

    // decor_building
    decor_building: parseSprite([
      "....................................",
      "....................................",
      "....................................",
      "....................................",
      "..AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..",
      "..AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..",
      "..AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..",
      "..AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBCCCCBBBDDDDBBBCCCCBBBCCCCBBB..",
      "..BBBBCCCCBBBDDDDBBBCCCCBBBCCCCBBB..",
      "..BBBBCCCCBBBDDDDBBBCCCCBBBCCCCBBB..",
      "..BBBBCCCCBBBDDDDBBBCCCCBBBCCCCBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBDDDDBBBCCCCBBBCCCCBBBCCCCBBB..",
      "..BBBBDDDDBBBCCCCBBBCCCCBBBCCCCBBB..",
      "..BBBBDDDDBBBCCCCBBBCCCCBBBCCCCBBB..",
      "..BBBBDDDDBBBCCCCBBBCCCCBBBCCCCBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBCCCCBBBCCCCBBBCCCCBBBCCCCBBB..",
      "..BBBBCCCCBBBCCCCBBBCCCCBBBCCCCBBB..",
      "..BBBBCCCCBBBCCCCBBBCCCCBBBCCCCBBB..",
      "..BBBBCCCCBBBCCCCBBBCCCCBBBCCCCBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBCCCCBBBCCCCBBBCCCCBBBDDDDBBB..",
      "..BBBBCCCCBBBCCCCBBBCCCCBBBDDDDBBB..",
      "..BBBBCCCCBBBCCCCBBBCCCCBBBDDDDBBB..",
      "..BBBBCCCCBBBCCCCBBBCCCCBBBDDDDBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBCCCCBBBCCCCBBBDDDDBBBCCCCBBB..",
      "..BBBBCCCCBBBCCCCBBBDDDDBBBCCCCBBB..",
      "..BBBBCCCCBBBCCCCBBBDDDDBBBCCCCBBB..",
      "..BBBBCCCCBBBCCCCBBBDDDDBBBCCCCBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBCCCCBBBDDDDBBBCCCCBBBCCCCBBB..",
      "..BBBBCCCCBBBDDDDBBBCCCCBBBCCCCBBB..",
      "..BBBBCCCCBBBDDDDBBBCCCCBBBCCCCBBB..",
      "..BBBBCCCCBBBDDDDBBBCCCCBBBCCCCBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.."
    ], { '.':null,'A':'#b026ff','B':'#12082a','C':'#ff66ff','D':'#1a1040' }),

    // decor_torch
    decor_torch: parseSprite([
      "............",
      "............",
      "......A.....",
      "....AABAA...",
      "...AAAAAAA..",
      "...AAAAAAA..",
      "..AAACAAAAA.",
      "...AAAAAAA..",
      "...AAAAAAA..",
      "....AAAAA...",
      ".....DAD....",
      ".....DDD....",
      ".....DDD....",
      ".....DDD....",
      ".....DDD....",
      ".....DDD....",
      ".....DDD....",
      ".....DDD....",
      ".....DDD....",
      ".....DDD....",
      ".....DDD....",
      ".....DDD....",
      ".....DDD....",
      ".....DDD...."
    ], { '.':null,'A':'#ff9933','B':'#ffe088','C':'#ff4422','D':'#5a3a20' }),

    // decor_crater
    decor_crater: parseSprite([
      "............................",
      "............................",
      "............................",
      "............AAAAA...........",
      "........AAAAAAAAAAAAA.......",
      "......AAAABBBBBBBBBAAAA.....",
      ".....AAABBBBBBBBBBBBBAAA....",
      "....AABBBBBBBBCBBBBBBBBAA...",
      "...AAABBBBBCCCCCCCBBBBBAAA..",
      "...AABBBBBCCCCCCCCCBBBBBAA..",
      "..AAABBBBBCCCCCCCCCBBBBBAAA.",
      "..AABBBBBCCCCCCCCCCCBBBBBAA.",
      "..AAABBBBBCCCCCCCCCBBBBBAAA.",
      "...AABBBBBCCCCCCCCCBBBBBAA..",
      "...AAABBBBBCCCCCCCBBBBBAAA..",
      "....AABBBBBBBBCBBBBBBBBAA...",
      ".....AAABBBBBBBBBBBBBAAA....",
      "......AAAABBBBBBBBBAAAA.....",
      "........AAAAAAAAAAAAA.......",
      "............AAAAA...........",
      "............................",
      "............................"
    ], { '.':null,'A':'#5a5a65','B':'#2a2a35','C':'#1a1a22' }),

    // decor_rune
    decor_rune: parseSprite([
      "....................",
      "....................",
      ".........AAA........",
      "......AAAAAAAAA.....",
      ".....AAA..B..AAA....",
      "....AA.........AA...",
      "...AA...........AA..",
      "...AA..C........AA..",
      "...A.............A..",
      "..AA.............AA.",
      "..AAB.....B.....BAA.",
      "..AA.............AA.",
      "...A.............A..",
      "...AA...........AA..",
      "...AA...........AA..",
      "....AA.........AA...",
      ".....AAA..B..AAA....",
      "......AAAAAAAAA.....",
      ".........AAA........",
      "...................."
    ], { '.':null,'A':'#7b68ee','B':'#c0b0ff','C':'#ffffff' }),

    // decor_portal
    decor_portal: parseSprite([
      "..........................",
      "..........................",
      "..........................",
      "...........AAAAA..........",
      ".........AAAAAAAAA........",
      "........AAAAAAAAAAA.......",
      ".......AAA.......AAA......",
      "......AAA...BBB...AAA.....",
      ".....AAA..BBBBBBB..AAA....",
      ".....AA..BBB...BBB..AA....",
      "....AAA..B.......B..AAA...",
      "....AA..BB...C...BB..AA...",
      "....AA..B..CCCCC..B..AA...",
      "....A...B.CCCCCCC.B...A...",
      "...AA..BB.CCCCCCC.BB..AA..",
      "...AA..BB.CCCCCCC.BB..AA..",
      "...AA..B.CCCCDCCCC.B..AA..",
      "...AA..BB.CCCCCCC.BB..AA..",
      "...AA..BB.CCCCCCC.BB..AA..",
      "....A...B.CCCCCCC.B...A...",
      "....AA..B..CCCCC..B..AA...",
      "....AA..BB...C...BB..AA...",
      "....AAA..B.......B..AAA...",
      ".....AA..BBB...BBB..AA....",
      ".....AAA..BBBBBBB..AAA....",
      "......AAA...BBB...AAA.....",
      ".......AAA.......AAA......",
      "........AAAAAAAAAAA.......",
      ".........AAAAAAAAA........",
      "...........AAAAA..........",
      "..........................",
      ".........................."
    ], { '.':null,'A':'#7b68ee','B':'#a090ff','C':'#201060','D':'#ffffff' }),

    // decor_rock
    decor_rock: parseSprite([
      "........................",
      "........................",
      "........................",
      "...........AAA..........",
      ".......AAAAAAAAAAA......",
      ".....AABAAABBABABAAA....",
      "....AAAAABAABBAAABABA...",
      "...ABBAACAAABAABAAAABA..",
      "...ABBBAAAAAAABAAAAAAA..",
      "...AABAAABAAAAABAAAAAA..",
      "..AAAAAAABBBAABAAAAAAAA.",
      "...ABAAABABBAAAABAAABA..",
      "...ABAABAABAAAAAAAABBA..",
      "...AAAABAAAAAAABAAABBA..",
      "....AAAABABABBABBAABB...",
      ".....AAAAAAAAAAAAAAA....",
      ".......AAAAAAAAAAA......",
      "...........AAA.........."
    ], { '.':null,'A':'#4a4a55','B':'#2a2a35','C':'#7a7a88' }),

    // decor_spire
    decor_spire: parseSprite([
      "....AAAAAABAAAAA....",
      "....AAAAAAAAAAAA....",
      "....AAAAAAAAAAAA....",
      "....AAAAAAAAAAAA....",
      "....AAAAAAAAAAAA....",
      ".....AAAAAAAAAA.....",
      ".....AAAAAAAAAA.....",
      ".....AAAAAAAAAA.....",
      ".....CCCCCCCCCC.....",
      ".....CCCCCCCCCC.....",
      "......CCCCCCCC......",
      "......CCCCCCCC......",
      "......CCCCCCCC......",
      "......CCCCCCCC......",
      "......CCCCCCCC......",
      ".......CCCCCC.......",
      ".......CCCCCC.......",
      ".......CCCCCC.......",
      ".......CCCCCC.......",
      ".......CCCCCC.......",
      "........CCCC........",
      "........CCCC........",
      "........CCCC........",
      "........CCCC........",
      "........CCCC........",
      ".........CC.........",
      ".........CC.........",
      ".........CC.........",
      ".........CC.........",
      ".........CC.........",
      ".........CC.........",
      ".........CC.........",
      ".........CC.........",
      ".........CC.........",
      "....................",
      "...................."
    ], { '.':null,'A':'#8a8aa0','B':'#ffd700','C':'#5a5a70' }),

    // decor_ruin
    decor_ruin: parseSprite([
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..............................",
      "..AAAAAAAAAAAAAAAAAAAAAAAAAA..",
      "..AAAAAAAAAAAAAAAAAAAAAAAAAA..",
      "..AAAAAAAAAAAAAAAAAAAAAAAAAA..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBCCCBBCCCBBCCCBBCCCBBCCCB..",
      "..BBCCCBBCCCBBCCCBBCCCBBCCCB..",
      "..BBCCCBBCCCBBCCCBBCCCBBCCCB..",
      "..BBCCCBBCCCBBCCCBBCCCBBCCCB..",
      "..BBCCCBBCCCBBCCCBBCCCBBCCCB..",
      "..BBCCCBBCCCBBCCCBBCCCBBCCCB..",
      "..BBCCCBBCCCBBCCCBBCCCBBCCCB..",
      "..BBCCCBBCCCBBCCCBBCCCBBCCCB..",
      "..BBCCCBBCCCBBCCCBBCCCBBCCCB..",
      "..BBCCCBBCCCBBCCCBBCCCBBCCCB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBB..",
      "..BBBBBBBBBBBBBBBBBBBBBBBBBB.."
    ], { '.':null,'A':'#5a3560','B':'#3a2540','C':'#2a1530' }),

    // decor_altar
    decor_altar: parseSprite([
      "......................",
      "......................",
      "......................",
      "......................",
      ".......AAAAAAAA.......",
      ".......AAAABAAA.......",
      ".......AAAAAAAA.......",
      "......AAAAAAAAAAA.....",
      "....AAAAACAAACA.AAA...",
      "...AA..AAAAAAAA...AA..",
      "...AA..AAAAAAAA...AA..",
      "..AA...AAAAAAAA....AA.",
      "..AA...............AA.",
      "..AA...............AA.",
      "...AA.............AA..",
      "...AA.............AA..",
      "....AAA.........AAA...",
      "......AAAAA.AAAAA.....",
      ".........AAAAA........",
      "......................"
    ], { '.':null,'A':'#ff8c00','B':'#ffffff','C':'#ffd080' }),

    // decor_holo
    decor_holo: parseSprite([
      "........................",
      "........................",
      "..........AAAAA.........",
      "........AAAAAAAAA.......",
      "......AAAA.....AAAA.....",
      ".....AAA.........AAA....",
      "....AAA...........AAA...",
      "....AA.....BBB.....AA...",
      "...AA....BB...BB....AA..",
      "...AA...BB.....BB...AA..",
      "..AA....B.......B....AA.",
      "..AA...B.........B...AA.",
      "..AA...B....C....B...AA.",
      "..AA...B.........B...AA.",
      "..AA....B.......B....AA.",
      "...AA...BB.....BB...AA..",
      "...AA....BB...BB....AA..",
      "....AA.....BBB.....AA...",
      "....AAA...........AAA...",
      ".....AAA.........AAA....",
      "......AAAA.....AAAA.....",
      "........AAAAAAAAA.......",
      "..........AAAAA.........",
      "........................"
    ], { '.':null,'A':'#00f5ff','B':'#88ffff','C':'#ffffff' }),

    // decor_target
    decor_target: parseSprite([
      "....................",
      "..........A.........",
      ".........AAA........",
      "......AAAAAAAAA.....",
      ".....AAA..A..AAA....",
      "....AA....A....AA...",
      "...AA.....A.....AA..",
      "...AA...A.A.A...AA..",
      "...A...A..A..A...A..",
      "..AA......A......AA.",
      ".AAAAAAAAAAAAAAAAAAA",
      "..AA......A......AA.",
      "...A...A..A..A...A..",
      "...AA...A.A.A...AA..",
      "...AA.....A.....AA..",
      "....AA....A....AA...",
      ".....AAA..A..AAA....",
      "......AAAAAAAAA.....",
      ".........AAA........",
      "..........A........."
    ], { '.':null,'A':'#00f5ff' }),

    // decor_neon
    decor_neon: parseSprite([
      "..............................",
      "..............................",
      ".....A.........A..............",
      ".BBBBBBBBBBBBBBBBBBBBBBBBBBBB.",
      ".BCCCCCCCCCCCCCCCCCCCCCCCCCCB.",
      ".BCCCCCCCCCCCCCCCCCCCCCCCCCCB.",
      ".BCCCCCCCCCCCCCCCCCCCCCCCCCCB.",
      ".BBBBBBBBBBBBBBBBBBBBBBBBBBBB.",
      "..............................",
      "..............................",
      "..............................",
      ".............................."
    ], { '.':null,'A':'#ffffff','B':'#b026ff','C':'#ff66ff' }),

    // decor_lava
    decor_lava: parseSprite([
      "..........................",
      "..........................",
      "............AAA...........",
      ".......AAAAAAAAAAAAA......",
      "....AAAAAAAABBBAAAAAAAA...",
      "...AAAAABBBBBBBBBBBAAAAA..",
      "..AAAABBBBCBBBBBBBBBBAAAA.",
      "..AAAABBBBBBBBBBBBBBBAAAA.",
      ".AAAABBBBBBBBBBBCBBBBBAAAA",
      "..AAAABBBBBBBBBBBBBBBAAAA.",
      "..AAAABBBBBBBBBBBBBBBAAAA.",
      "...AAAAABBBBBBBBBBBAAAAA..",
      "....AAAAAAAABBBAAAAAAAA...",
      ".......AAAAAAAAAAAAA......",
      "............AAA...........",
      ".........................."
    ], { '.':null,'A':'#5a1510','B':'#ff4422','C':'#ffaa44' }),

    // decor_stalactite
    decor_stalactite: parseSprite([
      "...AAAAAAAA...",
      "...AAAAAAAA...",
      "...AAAAAAAA...",
      "...AAAAAAAA...",
      "...AAAAAAAA...",
      "....AAAAAA....",
      "....AAAAAA....",
      "....AAAAAA....",
      "....AAAAAA....",
      "....AAAAAA....",
      "....AAAAAA....",
      ".....AAAA.....",
      ".....AAAA.....",
      ".....AAAA.....",
      ".....AAAA.....",
      ".....AAAA.....",
      ".....AAAA.....",
      "......AA......",
      "......AA......",
      "......AA......",
      "......AA......",
      "......AA......",
      "......AA......",
      "......AA......",
      "......AA......",
      "......AA......",
      "......AA......",
      "......AA......",
      "..............",
      ".............."
    ], { '.':null,'A':'#4a2020' }),

    // decor_flag
    decor_flag: parseSprite([
      "..AA............",
      "..AABBBBBBBBBBB.",
      "..AABBBBBBBBBBB.",
      "..AABBBCBBBBBBB.",
      "..AABBBBBCBBBBB.",
      "..AABBBBBBBBBBB.",
      "..AABBBBBBBBBBB.",
      "..AABBBBBBBBBBB.",
      "..AABBBBBBBBBBB.",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............",
      "..AA............"
    ], { '.':null,'A':'#888888','B':'#dddddd','C':'#ff2200' }),

    // decor_fog
    decor_fog: parseSprite([
      "..............................",
      "..............AAA.............",
      "........AAAAAAAAAAAAAAA.......",
      ".....AAAAAAAAAAAAAAAAAAAAA....",
      "...AAAAAAAAAAAAAAAAAAAAAAAAA..",
      "..AAAAAAAAAAAAAAAAAAAAAAAAAAA.",
      "..AAAAAAAAAAAAAAAAAAAAAAAAAAA.",
      ".AAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "..AAAAAAAAAAAAAAAAAAAAAAAAAAA.",
      "..AAAAAAAAAAAAAAAAAAAAAAAAAAA.",
      "...AAAAAAAAAAAAAAAAAAAAAAAAA..",
      ".....AAAAAAAAAAAAAAAAAAAAA....",
      "........AAAAAAAAAAAAAAA.......",
      "..............AAA............."
    ], { '.':null,'A':'#6a3088' }),

    // decor_vine
    decor_vine: parseSprite([
      ".....A......",
      ".....A......",
      ".....A......",
      "......A.....",
      "......A.....",
      "......A.....",
      ".....A......",
      "...B.A......",
      ".....A......",
      "......A.....",
      "......A.....",
      "......A.....",
      ".....A......",
      ".....A......",
      ".....A......",
      "......A.....",
      "......A.B...",
      "......A.....",
      ".....A......",
      ".....A......",
      ".....A......",
      "......A.....",
      "......A.....",
      "......A.....",
      ".....A......",
      ".....A......",
      ".....A......",
      "......A....."
    ], { '.':null,'A':'#1a5a1a','B':'#2a8a2a' }),

    // decor_grass
    decor_grass: parseSprite([
      "..............",
      "..............",
      ".A.....A......",
      ".B.A...B.A....",
      ".B.B.A.B.B.A..",
      ".B.B.B.B.B.B..",
      "..B.BB..B.BB..",
      "..B.B.B.B.B.B.",
      "..B.B.B.B.B.B.",
      "..B.B.B.B.B.B."
    ], { '.':null,'A':'#5dff6a','B':'#2d8a28' }),

    // decor_bush
    decor_bush: parseSprite([
      "....................",
      "....................",
      ".........AAA........",
      ".....AAAAAAAAAAA....",
      "....AABAAAAAAABAA...",
      "...BBBBCBBABBBBBBB..",
      "..BBBBBBBBBBBCBBBBB.",
      "..BBBBBBBBBBBBBBBBB.",
      ".BBBBBBBBBBBBBBBBBBB",
      "..BBBBBBBBBBBBBBBBB.",
      "..BBBBBBBBBBBBBBBBB.",
      "...BBBBBBBABBBBBBB..",
      "....AABAAAAAAABAA...",
      ".....AAAAAAAAAAA...."
    ], { '.':null,'A':'#1a5a20','B':'#0d4a14','C':'#39ff14' }),

    // decor_flower
    decor_flower: parseSprite([
      "............",
      "......A.....",
      "....AAAAA...",
      "....BAAAB...",
      "...AAACAAA..",
      "....AAAAA...",
      "....AAAAA...",
      ".....DA.....",
      ".....DD.....",
      ".....DD.....",
      ".....DD.....",
      ".....DD.....",
      ".....DD.....",
      ".....DD....."
    ], { '.':null,'A':'#ff66aa','B':'#ff99cc','C':'#ffd700','D':'#2a8a2a' }),

    // decor_fern
    decor_fern: parseSprite([
      "................",
      "................",
      "................",
      "................",
      "..A..A..A.......",
      "...A.BA.B.......",
      "...BA.BAB.......",
      "....B.BBB.......",
      "....BBBBB.......",
      ".....BBBB.......",
      ".....BBBB.......",
      "......BBB.......",
      "......BBB.......",
      ".......BB.......",
      ".......BB.......",
      "........B.......",
      "........B.......",
      "................"
    ], { '.':null,'A':'#3aaa40','B':'#1f6a28' }),

    // decor_crate
    decor_crate: parseSprite([
      "................",
      "................",
      ".AAAAAAABAAAAAA.",
      ".ACCCCCCBCCCCCA.",
      ".ACCCCCCBCCCCCA.",
      ".ACCCCCCBCCCCCA.",
      ".ACCCCCCBCCCCCA.",
      ".BBBBBBBBBBBBBB.",
      ".ACCCCCCBCCCCCA.",
      ".ACCCCCCBCCCCCA.",
      ".ACCCCCCBCCCCCA.",
      ".ACCCCCCBCCCCCA.",
      ".AAAAAAABAAAAAA.",
      "................"
    ], { '.':null,'A':'#8a6230','B':'#5a3a18','C':'#a87838' }),

    // decor_barrel
    decor_barrel: parseSprite([
      "..............",
      ".......A......",
      "....AAAAAAA...",
      "...AAAAAAAAA..",
      "..BBBBBBBBBB..",
      "..BBBBBBBBBBA.",
      "..CCCCCCCCCCA.",
      "..BBBBBBBBBBA.",
      ".ABBBBBBBBBBAA",
      "..BBBBBBBBBBA.",
      "..CCCCCCCCCCA.",
      "..BBBBBBBBBBA.",
      "...AAAAAAAAA..",
      "...AAAAAAAAA..",
      "....AAAAAAA...",
      ".......A......"
    ], { '.':null,'A':'#6a4020','B':'#8a5530','C':'#d0a040' }),

    // decor_bones
    decor_bones: parseSprite([
      "..................",
      "..................",
      "...A...........A..",
      ".AAAAA.......AAAAA",
      ".AABAACCCCCCCAABAA",
      "AAAAAAACCCCCAAAAAA",
      ".AAAAA.......AAAAA",
      ".AAAAA.......AAAAA",
      "...A...........A..",
      ".................."
    ], { '.':null,'A':'#f0ead8','B':'#ffffff','C':'#e8e0c8' }),

    // decor_lamp
    decor_lamp: parseSprite([
      "............",
      "............",
      "...AAAAAA...",
      "...AABAAA...",
      "...AAAAAA...",
      "...AAACAA...",
      "...AAAAAA...",
      "...AAAAAA...",
      "...AAAAAA...",
      ".....DD.....",
      ".....DD.....",
      ".....DD.....",
      ".....DD.....",
      ".....DD.....",
      ".....DD.....",
      ".....DD.....",
      ".....DD.....",
      ".....DD.....",
      ".....DD.....",
      ".....DD....."
    ], { '.':null,'A':'#ffd060','B':'#ffffff','C':'#ff8800','D':'#555566' }),

    // decor_debris
    decor_debris: parseSprite([
      "................",
      "................",
      "................",
      "....A...........",
      "..BBBBB....C....",
      "..BBBBB.DDDDDD..",
      "..BBBBB.DDDDDD..",
      "..BBBBB.DDDDDD..",
      "................",
      "................"
    ], { '.':null,'A':'#8a8a90','B':'#5a5a60','C':'#6a6a70','D':'#3a3a45' }),

    // decor_statue
    decor_statue: parseSprite([
      "................",
      "................",
      "........A.......",
      ".....AAAAAAA....",
      "....AAAAAAAAA...",
      "....AAAAAAAAA...",
      "....AABAAABAA...",
      "...AAAAAAAAAAA..",
      "....AAAAAAAAA...",
      "....AAAAAAAAA...",
      "....AAAAAAAAA...",
      ".....AAAAAAA....",
      ".....CCCACC.....",
      ".....CCCCCC.....",
      ".....CCCCCC.....",
      ".....CCCCCC.....",
      ".....CCCCCC.....",
      ".....CCCCCC.....",
      ".....CCCCCC.....",
      ".....CCCCCC.....",
      ".....CCCCCC.....",
      ".....CCCCCC.....",
      ".....CCCCCC.....",
      ".....CCCCCC.....",
      "...DDDDDDDDDD...",
      "...DDDDDDDDDD...",
      "...DDDDDDDDDD...",
      "...DDDDDDDDDD..."
    ], { '.':null,'A':'#8a8070','B':'#222','C':'#7a7060','D':'#6a6050' })
  };
  function drawSprite(ctx, sprite, x, y, scale, flipX) {
    if (!sprite) return;
    const s = scale || PX;
    const dw = sprite.w * s, dh = sprite.h * s;
    ctx.imageSmoothingEnabled = false;
    if (sprite.canvas) {
      ctx.save();
      if (flipX) { ctx.translate(x + dw, y); ctx.scale(-1, 1); ctx.drawImage(sprite.canvas, 0, 0, sprite.w, sprite.h, 0, 0, dw, dh); }
      else ctx.drawImage(sprite.canvas, 0, 0, sprite.w, sprite.h, x, y, dw, dh);
      ctx.restore(); return;
    }
    const { w, pixels } = sprite;
    for (let i = 0; i < pixels.length; i++) {
      const color = pixels[i]; if (!color) continue;
      const col = i % w, row = Math.floor(i / w);
      ctx.fillStyle = color;
      ctx.fillRect(x + (flipX ? w - 1 - col : col) * s, y + row * s, s, s);
    }
  }
  function drawSpriteCentered(ctx, sprite, cx, cy, scale, facingLeft) {
    if (!sprite) return;
    const s = scale || PX;
    drawSprite(ctx, sprite, cx - (sprite.w * s) / 2, cy - (sprite.h * s) / 2, s, facingLeft);
  }
  function drawPixelCircle(ctx, cx, cy, r, color) {
    ctx.fillStyle = color;
    const rr = Math.max(1, Math.round(r));
    for (let y = -rr; y <= rr; y++) for (let x = -rr; x <= rr; x++)
      if (x*x + y*y <= rr*rr) ctx.fillRect(Math.round(cx)+x, Math.round(cy)+y, 1, 1);
  }
  window.PixelSprites = { SPRITES, PX, drawSprite, drawSpriteCentered, drawPixelCircle, bakeSprite };
})();
